default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: your_username
  password: your_password
  port: your_port

development:
  <<: *default
  database: desafio_backend_development

test:
  <<: *default
  database: desafio_backend_test

production:
  <<: *default
  database: desafio_backend_production
  username: desafio_backend
  password: <%= ENV["DESAFIO_BACKEND_DATABASE_PASSWORD"] %>
